-- FutureMakers Free Guide Hub schema
-- Run once in the Supabase SQL Editor for project zuqmokdsvbwaolqkwask.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safe when reusing the earlier FutureMakers profile table.
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists display_name text;

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null,
  category text not null default 'Guide',
  resource_url text not null,
  action_label text not null default 'Open resource',
  sort_order integer not null default 0,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.resource_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  resource_slug text not null references public.resources(slug) on update cascade on delete cascade,
  opened_at timestamptz,
  completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, resource_slug)
);

alter table public.profiles enable row level security;
alter table public.resources enable row level security;
alter table public.resource_progress enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "resources_read_published" on public.resources;
create policy "resources_read_published" on public.resources for select to authenticated using (is_published = true);

drop policy if exists "progress_select_own" on public.resource_progress;
create policy "progress_select_own" on public.resource_progress for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "progress_insert_own" on public.resource_progress;
create policy "progress_insert_own" on public.resource_progress for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "progress_update_own" on public.resource_progress;
create policy "progress_update_own" on public.resource_progress for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select on public.resources to authenticated;
grant select, insert, update on public.resource_progress to authenticated;

insert into public.resources (slug, title, description, category, resource_url, action_label, sort_order, is_published)
values
  ('ai-income-checklist', 'AI Income Path Checklist', 'Identify what you know, who it can help, and the first useful offer you can test.', 'Start here', '/free-checklist', 'Open the checklist', 10, true),
  ('futuremakers-tools', 'FutureMakers Free Tools', 'Use practical tools to examine a market, shape an offer, and turn an idea into a buildable plan.', 'Build', '/ai-pays-off/tools', 'Explore the tools', 20, true),
  ('ai-personal-creator', 'AI Spokesperson Showcase', 'See how a consistent AI spokesperson and video-content system can work for a real business.', 'Create', '/ai-personal-creator', 'Watch the showcase', 30, true)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  resource_url = excluded.resource_url,
  action_label = excluded.action_label,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
